# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

# TODO: Change the workflow name to something more specific
name: Python application

# This defines the triggers for the workflow
# i.e. when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# This defines the permissions for the workflow
permissions:
  contents: read

jobs:
  build:

    # This defines the type of machine to run the job on
    runs-on: ubuntu-latest

    steps:

    # This step copies your repository code to the runner
    - uses: actions/checkout@v4

    # This step sets up Python on the runner
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

    # This step installs uv
    - name: Install uv
      uses: astral-sh/setup-uv@v3



    # The next steps use *run* to execute commands on the runner
    # This is just like typing commands in the Codespace terminal

    # This step installs dependencies
    - name: Install dependencies
      run: |
        uv sync

    # This step runs unit tests with pytest
    - name: Test with pytest
      run: |
        uv run -m pytest

    # This step runs the linter against the codebase
    - name: Lint with ruff
      run: |
        uvx ruff check .

    - name: Check formatting with black
      run: |
        uvx ruff formt

    - name: Type check with mypy
      run: |
        uvx ty check 
      